yarnPath: .yarn/releases/yarn-3.2.0.cjs
nodeLinker: "pnp"
pnpMode: loose
packageExtensions:
  "@types/styled-components@*":
    dependencies:
      "hoist-non-react-statics": "*"
  "@types/react@*":
    dependencies:
      "scheduler": "*"
  "styled-components@*":
    dependencies:
      "babel-plugin-macros": "*"
      "react-is": "*"
  "@storybook/preview-web@*":
    dependencies:
      "@types/qs": "*"
  "@storybook/components@*":
    peerDependencies:
      "@emotion/styled-base": "*"
    dependencies:
      "@storybook/api": "*"
      "@emotion/styled-base": "*"
      "react-textarea-autosize": "*"
  "@storybook/theming@*":
    dependencies:
      "@emotion/utils": "*"
      "@emotion/serialize": "*"
  "@storybook/addon-docs@*":
    dependencies:
      "react-is": "*"
      "webpack": "*"
  "@storybook/addon-a11y@*":
    dependencies:
      "react-is": "*"
  "@storybook/addon-actions@*":
    dependencies:
      "react-is": "*"
  "@storybook/addon-backgrounds@*":
    dependencies:
      "react-is": "*"
  "@storybook/addon-controls@*":
    dependencies:
      "react-is": "*"
  "@storybook/addon-measure@*":
    dependencies:
      "react-is": "*"
  "@storybook/builder-webpack4@*":
    dependencies:
      "@emotion/core": "*"
      "react-is": "*"
  "@storybook/core-client@*":
    dependencies:
      "@emotion/core": "^10.0.27"
  "@storybook/docs-tools@*":
    dependencies:
      "react": "^16.14.0"
      "react-dom": "^16.14.0"
  "@storybook/core-common@*":
    dependencies:
      "react": "^16.8.0"
      "react-dom": "^16.8.0"
  "rollup@*":
    dependencies:
      "source-map-support": "*"
  "jest-styled-components@*":
    dependencies:
      "pretty-format": "*"
  "jest@*":
    dependencies:
      "@testing-library/jest-dom": "*"
  "debug@*":
    dependencies:
      "supports-color": "*"
  "node-fetch@*":
    dependencies:
      "encoding": "*"
  "ts-node@*":
    dependencies:
      "@types/node": "*"
  "babel-loader@*":
    dependencies:
      "@babel/core": "^7.0.0"
  "@phenomnomnominal/tsquery@*":
    dependencies:
      "typescript": "^3 || ^4"
  "@dnd-kit/modifiers@*":
    peerDependencies:
      "react": ">=16.8.0"
  "upath2@*":
    dependencies:
      "@types/node": "*"
  "@figspec/react@*":
    dependencies:
      "react": "^16.14.0"
  "@babel/preset-env@*":
    dependencies:
      "@babel/core": "^7.0.0-0"
  "@babel/plugin-transform-react-jsx@*":
    dependencies:
      "@babel/core": "^7.0.0-0"
