yarnPath: .yarn/releases/yarn-3.2.0.cjs
nodeLinker: "pnp"
pnpMode: loose
packageExtensions:
  "styled-components@*":
    dependencies:
      "babel-plugin-macros": "*"
      "react-is": "*"
  "@types/styled-components@*":
    dependencies:
      "hoist-non-react-statics": "*"
  "@storybook/core@*":
    peerDependencies:
      "@babel/core": "^7.0.0-0"
  "@storybook/ui@*":
    peerDependencies:
      "@emotion/core": "^10.0.27"
  "@storybook/preview-web@*":
    dependencies:
      "@types/qs": "*"
  "@storybook/components@*":
    peerDependencies:
      "react-is": "*"
      "@emotion/styled-base": "*"
    dependencies:
      "@storybook/api": "*"
      "@emotion/styled-base": "*"
      "react-textarea-autosize": "*"
  "@storybook/theming@*":
    dependencies:
      "@emotion/utils": "*"
      "@emotion/serialize": "*"
  "@types/react@*":
    dependencies:
      "scheduler": "*"
  "rollup@*":
    dependencies:
      "source-map-support": "*"
  "jest-styled-components@*":
    dependencies:
      "pretty-format": "*"
  "jest@*":
    dependencies:
      "@testing-library/jest-dom": "*"
  